"use client";

export default function HeroScrollIndicator() {
  return (
    <div
      data-hero="scroll-indicator"
      className="
        pointer-events-none
        absolute
        bottom-16
        left-1/2
        z-30
        flex
        -translate-x-1/2
        flex-col
        items-center
        gap-2
      "
    >
      <span
        className="
          text-[10px]
          font-medium
          uppercase
          tracking-[0.35em]
          text-white/35
        "
      >
        Scroll
      </span>

      <div
        className="
          flex
          h-12
          w-7
          items-start
          justify-center
          rounded-full
          border
          border-white/20
          bg-white/[0.02]
          p-1
        "
      >
        <span
          className="
            h-2
            w-2
            rounded-full
            bg-cyan-300
            shadow-[0_0_12px_rgba(103,232,249,0.7)]
            animate-bounce
          "
        />
      </div>
    </div>
  );
}